{% set version = "3.4.0" %}

package:
  name: sgpp
  version: {{ version }}

source:
  fn: sgpp-{{ version }}.tar.gz
  url: https://github.com/SGpp/SGpp/archive/v{{ version }}.tar.gz
  sha256: 450d4002850b0a48c561abe221b634261ca44eee111ca605c3e80797182f40b3
  #patches:
  "  - osx.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - scons
    - setuptools
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy

test:
  imports:
    - pysgpp

about:
  home: http://sgpp.sparsegrids.org/
  license: BSD 3-Clause
  license_file: LICENSE.md
  summary: A numerical library for adaptive Sparse Grids

extra:
  recipe-maintainers:
    - jschueller
