travis:
  secure:
    BINSTAR_TOKEN: m0tXsIwgmAk7XpsV1G5EdD+xMGHyi5guyGRH4N6xRE3nmJdlnZ1mwzng1YsEMj+jexP4K0RcO7g8riE5GWa8b/Tx04GHNECSpYZcQ6gNZXVmpbviok+srGKHeZMe2Db9pOmkx7ENB088ICZP8Mzw5nLV49wROKYr6m681SSvnCl2fKwagAvxC3Pn32IESj+eFLJEPYnAnAtDWUwh0zdc30WKz05LsMxLB06jNQbA8QlhgPNlRemLyzKt6irdiDlskQtOpHq4ROWxe0B+SR2RCiun6Phb4j7EQRoEkyQE0Khf4bbPS69BRzj50HysEkfvu8y6VabrNwYsZTHhl42CfNKHyp16oh0/nBdkzVOzSRvh47pj0jDX7P35OPm/X5Sz+AOuaNImDtrD9kzt4h1oaqbNlbE6SAIaslPgzbUUXzHZw1A6ZlaTvaKNTWZ/cShxy8nYiCYCu7W0kReT3ij0T1ItCfSO2qW+681v1SxW2HC0nnOHZGMG0n8WxFNpIqajMaddaWqCJxw6oLIroDV5aZkWppPL/CBlwXGY7NhjXw6t2ivDWlcjtiOKu/MJQYzS6YbYmJJFy3ep4pz5PM23Am5O1fQdvBxdPklHjM97hwd3gujpB4jmPqf3N/oyc/JNkB5ZI+jct00HQnWyPAlQGl0jgCG6oCPJDztek6PF/7M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
